### ISSUE TITLE
Reconnect to Oracle not working for queries

### ISSUE THREAD

**Issue by vpeltola** [knex/knex#3373]
# Environment

Knex version: 0.19.1
Database + version: 12.2.0.1
OS: Fedora 30
@atiertant 

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

If an oracle database is restarted, knex (still) loses the connection and is unable to reconnect in some cases, specifically at least when performing queries.

knex version 0.18 attempted to fix this problem in issue https://github.com/tgriesser/knex/pull/2608 in this commit 
https://github.com/tgriesser/knex/commit/6e5e296ede2e8921082023c147c7b2e22e5f79a4

ORA-xxxx error messages were added to the isConnectionError(err) function in knex/lib/dialects/oracle/utils.js file.  The function checks if err.message *starts* with a specific ORA-xxxx or NJS-xxx error message and if so returns true.

However, this does not always work.  For example, when attempting to run a query after a database restart, the connection error is not detected, because the err.message string looks like this:
```
select * from mytable - ORA-03113: end-of-file on communication channel
```
As stated before, isConnectionError() requires "ORA-03113" to be at the very beginning of the message, which is how it comes out of the oracledb module.

The root of problem seems to be caused by knex/lib/client.js function query(), which prepends the query to err.message (knex version 0.19.1):
```
158     return this._query(connection, obj).catch((err) => {
159       err.message =
160         this._formatQuery(obj.sql, obj.bindings) + ' - ' + err.message;
```
If line 160 was reversed so that the original database error message came first, then the isConnectionError() function should work (or even better, don't change err.message at all)
```
159       err.message =
160         err.message + ' - ' + this._formatQuery(obj.sql, obj.bindings);
```

**Comment by kibertoad** [comment]
@vpeltola Would you consider submitting PR with test for this?

**Comment by ahmad380360** [comment]
اعاده. ظبط القارب. وشكرا

**Comment by elhigu** [comment]
![adjust-the-boat-thanks](https://user-images.githubusercontent.com/696345/67365760-e519cf80-f57a-11e9-81fb-7005961346a5.png)

😸

**Comment by abskmj** [comment]
@kibertoad can I raise a PR for this ?

**Comment by elhigu** [comment]
@abskmj this has been tried to be fixed couple of times already some kind of integration test would be nice to be included if you start fixing this.

**Comment by abskmj** [comment]
I will start with a simple PR which has the right ORA codes. Do I need to create separate issues to resolve this with multiple PRs?

**Comment by elhigu** [comment]
Thanks! The whole bug should be fixed in a single PR.

**Comment by abskmj** [comment]
ORA codes are corrected part of PR #3498

**Comment by kibertoad** [comment]
@vpeltola Could you please try 0.20.1 and see if problem was fixed?

**Comment by vpeltola** [comment]
Hello!
I just rested this.  First, as a sanity check, I tested with knex@0.19.1 + oracledb@4.1.2 which still failed as in the original bug description.
I then updated to knex@0.20.7, re-tested and the problem no longer happens.
Looks like the problem has been corrected.  Thank you!
