### ISSUE TITLE
Knex doesn't support knexfiles written in ECMAScript Modules

### ISSUE THREAD

**Issue by boggddan** [knex/knex#3571]
Hi,
Knex-cli does not work with [ECMAScript Modules](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field) when i run migrate.

# Environment
node: 13.3.0
knex: 0.20.4

package.json
```json
{
  "type": "module",
  "dependencies": {
   ...
    "knex": "^0.20.4",
    ...
  }
}
```
knexfile.js

```js
import './config.js';

export default {
  client: 'postgresql',
  connection: {
    host: process.env.ACCOUNT_SERVER_POSTGRES_HOST,
    port: process.env.ACCOUNT_SERVER_POSTGRES_PORT,
    database: process.env.ACCOUNT_SERVER_POSTGRES_DB,
    user: process.env.ACCOUNT_SERVER_POSTGRES_USER,
    password: process.env.ACCOUNT_SERVER_POSTGRES_PASSWORD
  }
};
```

```bash
NODE_ENV=development npx knex migrate:latest
```

Output error:

```bash
(node:2107) Warning: require() of ES modules is not supported.
require() of /home/user/Project/coffee-print-account-server/knexfile.js from /home/user/Project/coffee-print-account-server/node_modules/knex/bin/cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename knexfile.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/user/Project/coffee-print-account-server/package.json.
internal/modules/cjs/loader.js:1163
      throw new ERR_REQUIRE_ESM(filename);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/user/Project/coffee-print-account-server/knexfile.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at initKnex (/home/user/Project/coffee-print-account-server/node_modules/knex/bin/cli.js:45:9)
    at Command.<anonymous> (/home/user/Project/coffee-print-account-server/node_modules/knex/bin/cli.js:184:17)
    at Command.listener (/home/user/Project/coffee-print-account-server/node_modules/knex/node_modules/commander/index.js:360:8)
    at Command.emit (events.js:219:5)
    at Command.parseArgs (/home/user/Project/coffee-print-account-server/node_modules/knex/node_modules/commander/index.js:799:12) {
  code: 'ERR_REQUIRE_ESM'
}
```

Thank's

**Comment by lorefnon** [comment]
So far ES modules are not explicitly supported by Knex. 

I guess to support this, we need to: 

1. Detect whether knexfile/migration/seed file is a module (by looking at extension: mjs or looking at package.json type field).
2. In case of module, we can use [dynamic import](https://nodejs.org/api/esm.html#esm_code_package_json_code_code_type_code_field) instead of require if the environment supports. 

I can take this up if we are fine with supporting experimental APIs. Or we can wait until this is stabilized. I guess in near futures more and more people will start running into this. 

The entire ESM+CJS compatibility scenario is a mess.

**Comment by kibertoad** [comment]
@lorefnon wasn't module support declared stable in latest Node?

**Comment by lorefnon** [comment]
They made it possible to use without a flag. But stability level in docs is still marked as experimental.

**Comment by kibertoad** [comment]
@lorefnon My mistake. You are right :)

**Comment by adrianhelvik** [comment]
I am writing some code for a new project now. I'd rather use ESM than CommonJS or Babel, as the project is a long way from reaching production status. So I for one would be very happy if this was fixed!

**Comment by D10221** [comment]
Hi ,
@lorefnon , I can see we had the same idea :)
One thing I'm not convinced ....  is the 'import' keyword.
It will move the engine requirement up to v13 without experimental flags, ...because 
Node v8.x, v9.x needs '--experimental-modules' to avoid  syntax error "Unexpected token import"
Node v10, v11, v12 needs '--experimental-modules' to avoid  syntax error "Unexpected token export"
Node v13 works without '--experimental-modules'
or maybe I'm missing something there :)

I Also noticed that in [require-interop](https://github.com/knex/knex/blob/daf3200ab551c02988539c0a9afb3eb8a95adcdc/lib/util/require-interop.js) you are testing for the parent type=module or '.mjs' extension , nice move!

Before I started looking into this I tried using '[esm](https://github.com/standard-things/esm)' module 
it could be as simple as `require('esm')(module)(fileName)` instead of 'require-interop' , if you don't mind taking on another dependency.

Any thoughts? 
Thanks

**Comment by D10221** [comment]
Related to my previous comment on the 'esm' loader , I pushed a [branch](https://github.com/knex/knex/compare/master...D10221:%233571_('esm')) on my repo related to it
Includes a small test case that I ran on node v8/10/12 & 13 and it seems to be doing just right
Do you think it could be a better solution?

**Comment by lorefnon** [comment]
@D10221 Sorry, I didn't see your commit before. You can continue with your branch here, I don't mind discarding my PR.

I haven't looked very closely into esm module, but it looks promising.

**Comment by D10221** [comment]
@lorefnon No prob. at all ...I wouldn't mind dropping mine either.
I'll continue testing  the seeds/migrations with 'esm' ...
I stumble on a 'esm' [issue](https://github.com/standard-things/esm/issues/855) with package.type.module , it might defeat the purpose

**Comment by D10221** [comment]
I did setup a [repo](1), kind of a big gists, where I run the migrations,seeds and share the configration using almost exclusively ESM modules.
All that with ['esm'](2) loaded externally, without the need to touch knex source.  

The basic Idea is that you need to launch node with `-r esm`.  
So esm can handle the requires.  

It does get a bit noisy when your main package is type='module' or you want to share the "knexfile.js"

On the 'knexfile.js' note, making knex look into a 'default' export could be a simple nice addition.

[1]: https://github.com/D10221/knex-esm-migrations
[2]: https://github.com/standard-things/esm

**Comment by briandamaged** [comment]
FYI: It looks like the `0.20.8` release of Knex might have introduced basic support for ESM via the `--esm` command-line argument.

**Comment by edtownend** [comment]
@briandamaged does this flag work for you? I'm getting
```
require() of xxx/migrations/20200225083022_initial.js from xxx/node_modules/knex/lib/migrate/sources/fs-migrations.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

```
 when using this flag with `"type": "module"` set in package.json.

**Comment by D10221** [comment]
@edtownend 

that is 'node resolution'  complaining. 
you can stop it adding a 'non-module'  package.json file to your migrations directory (simply 'yarn init -y' then set to private).
or removing the type: 'module' from your main project file.

What node version are you using ? 
Where Is your migrations 'dir' in relative path terms to your src/ dir or main file if any :)  
Just curious :)

**Comment by edtownend** [comment]
@D10221 Bingo, that worked great thanks! That's using node v13.7.0 and the migrations dir is in the root of my project

**Comment by briandamaged** [comment]
Marking this as "Closed" since it appears that the issue has been resolved.

**Comment by rajsinghUSA** [comment]
> @edtownend
> 
> that is 'node resolution' complaining.
> you can stop it adding a 'non-module' package.json file to your migrations directory (simply 'yarn init -y' then set to private).
> or removing the type: 'module' from your main project file.
> 
> What node version are you using ?
> Where Is your migrations 'dir' in relative path terms to your src/ dir or main file if any :)
> Just curious :)

I tried adding a non-module package.json to my migrations and seed directories, but that still didn't resolve the issue. Only thing that worked was removing type:"module" from my main project file. Would prefer not to do the latter, however. Any idea on when knex will start supporting ESMs?

**Comment by D10221** [comment]
@rajsinghUSA 
it seems to me, that what you have experienced, is your ```package.json``` getting in the way.
the current node resolution algorithm won't let you 'import' stuff from you own package unless, it self, its a module.
You could try the 'esm' package to overcome that, 'by design', limitation.

**Comment by kevinfiol** [comment]
Perhaps I'm missing something, but I'm still having issues with this. I'm simply trying to use knex in a project using ES Modules, via the `"type:": module"` option in package.json on Node v14.5.0.

1. I saw https://github.com/knex/knex/pull/3829, and tried using a `knexfile.cjs` instead, but this results in an error: `Error: ENOENT: no such file or directory, open '../server/node_modules/knex/lib/migrate/stub/cjs.stub'`

2. That same ticket mentions `--esm` not working on Node >=14. I noticed the docs don't say anything about this. I believe it though, because it doesn't seem to help at all in my case. Results in the same `require() of ES modules is not supported.` error.

Wondering if anyone has a clean solution that doesn't involve removing `"type": "module"` from your project, or having to include something like https://github.com/standard-things/esm. I'm trying to avoid having to rope in another dependency just for Knex.

**Comment by rajsinghUSA** [comment]
For the record, I never got this resolved either. I keep having to remove `type: "module"` from `package.json` everytime I need to run migrate and seed.

**Comment by D10221** [comment]
For the above related comments, 

I did open a new [issue](https://github.com/knex/knex/issues/3937).
There is [linked pr](https://github.com/knex/knex/pull/3938) 
That should help make the 'esm' interop easier to implement,

**Comment by thefoxie** [comment]
> I tried adding a non-module package.json to my migrations and seed directories, but that still didn't resolve the issue. Only thing that worked was removing type:"module" from my main project file. Would prefer not to do the latter, however. Any idea on when knex will start supporting ESMs?

@rajsinghUSA I know your pain. I use Objectionjs and everything is written with ESM. I've used esm (the package) before, but managed to remove it from the project. I'm able to import and use the objection models inside my seeds but I need to remove `type: module` from `package.json` and run `npx knex --esm seed:run`, otherwise I get only errors. Btw found out that seeds got extensions option which is not documented at all.
```
"seeds": {
     "directory": "./seeds",
     "loadExtensions":[".js",".mjs",".cjs"]
}
```

**Comment by D10221** [comment]
At this point  I don't think it should be Knex's concern ... the entire esm/cjs story is quite broken ...
A library can/should only try import or require something... a module, but if the underlying platform can't make its mind on how to do it.. There is so much you can do about before becoming the platform/runtime  your self.

**Comment by tlhunter** [comment]
I believe this fixes the stub error (pointed out by @kevinfiol):

```js
  migrations: {
    tableName: 'knex_migrations',
    extension: 'mjs',
    loadExtensions: ['.mjs'],
    stub: 'migrations/_template.mjs',
  },
```

Basically, I think it's looking for an MJS file in the package directory but the authors don't seem to have one. So, you'll need to create your own.
