### ISSUE TITLE
Executable node/r not found on Linux

### ISSUE THREAD

**Issue by ldrick** [knex/knex#5455]
# Environment

Knex version: 2.4.1
Database + version: any
OS: Ubuntu 

# Bug

1. Running knex on Linux fails pretty early with the same behavior of this bug: #4614 . If I manually change within node_modules/.bin/knex from CRLF to LF it runs smoothly.

2. Error message
`/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.`

**Comment by kibertoad** [comment]
thanks, need to reconfigure new rig

**Comment by rannooo** [comment]
Ouch, this just broke our CICD production release flow. As a workaround I installed `sudo apt install dos2unix` and converted DOS line breaks to Unix line breaks with `dos2unix node_modules/knex/bin/cli.js`

**Comment by alizeegtd** [comment]
I also just got the issue 4 hours ago during migration and seed. Maybe a bug coming from a Knex dependency?

**Comment by kibertoad** [comment]
will fix tonight, it's a result of a different git configuration on my new computer :-/

**Comment by davesalomon** [comment]
A different (temporary) fix until a new version is published:

`package.json` before: `knex migrate:latest`
`package.json` after: `npx --yes crlf --set=LF node_modules/knex/bin/cli.js && knex migrate:latest`

**Comment by falkenhawk** [comment]
@kibertoad v2.4.1 has been released with CRLF (windows line endings) in all files. Line endings should be reverted to LF in all files, not only `cli.js`. renovatebot shows it clearly as all lines have been modified in all files.
https://app.renovatebot.com/package-diff?name=knex&from=2.4.0&to=2.4.1

**Comment by ripecosta** [comment]
@kibertoad Adding a `prettier --lint-different` step to the CI pipeline would catch these changes and avoid them in the future.

**Comment by yovasx2** [comment]
i am having 2.4.1 and still having the crlf problem

**Comment by kibertoad** [comment]
@ripecosta Thank you for the tip, added.
@ldrick can you please check if 2.4.2 solves the issue for you?

**Comment by ldrick** [comment]
@kibertoad Tahnk you very much, it works like a charm.

**Comment by beenotung** [comment]
This issue could be closed?

**Comment by dawson-conway** [comment]
When I download 2.4.2 this is resolved, but when I install 2.5.0 the issue returns and `bin/cli.js` has CRLF endings again.

**Comment by apoorv254** [comment]
I am using knex version 2.4.2 but still getting this error . Is there can be any other reason?
versions I am using
node - 16.16.0
yarn 1.22.19
knex 2.4.2

**Comment by paoesco** [comment]
Hello,
I can confirm that knex 2.5.0 has the issue on MacOS.

Running: 
```NODE_ENV=test y knex migrate:latest```
Error: 
```env: node\r: No such file or directory```

Node: 18.15.0
Yarn: 1.22.19
Knex: 2.5.0

**Comment by danielrhodes** [comment]
Any update on this? It's affecting production builds.

**Comment by OlivierCavadenti** [comment]
> Any update on this? It's affecting production builds.

I will release a new version this evening with auto formatting in LF command.

**Comment by OlivierCavadenti** [comment]
> Any update on this? It's affecting production builds.

Released https://github.com/knex/knex/releases/tag/2.5.1
Say me if all it's ok for you.

**Comment by beenotung** [comment]
FYI, if you install with npm/pnpm, the cli problem is auto fixed.
The cli problem caused by newline is not auto fixed if you install with yarn.

**Comment by notmedia** [comment]
When creating new migration file via knex migrate:make the EOLs' are in CRLF. Would be grate if you also change the default behaviour here.

**Comment by rubengmurray** [comment]
It appears this problem was fixed and has had no comment to the contrary since. Would someone on the thread care to confirm?

If so, `notmedia` maybe this comment warrants a separate issue opening?

> When creating new migration file via knex migrate:make the EOLs' are in CRLF. Would be grate if you also change the default behaviour here.

**Comment by rubengmurray** [comment]
@mercmobily for visibility

**Comment by mercmobily** [comment]
Thank you for reporting this issue about the CRLF line endings causing execution problems on Linux systems. This was indeed a significant problem that affected many users when knex 2.4.1 was released with Windows line endings.

This issue has been resolved in version 2.4.2 and subsequent releases. The problem occurred when knex 2.4.1 was accidentally published with CRLF (Windows) line endings instead of LF (Unix) line endings, causing the shebang line `#!/usr/bin/env node` in bin/cli.js to be interpreted incorrectly on Linux and macOS systems, resulting in the error "env: node\r: No such file or directory".

After reviewing the codebase and git history, I can confirm that multiple fixes have been implemented to prevent this from happening again. The initial fix was applied in version 2.4.2 through PR #5459, which added additional lint checks before publishing. Unfortunately, the issue briefly recurred in version 2.5.0 but was promptly fixed again in version 2.5.1 through PR #5460.

The current safeguards in place include an .editorconfig file that enforces LF line endings across all files:
```
end_of_line = lf
```

Additionally, prettier formatting is now part of the development workflow, helping to maintain consistent line endings. I've verified that the current version (3.1.0) has proper LF line endings in all critical files including bin/cli.js.

Testing the current state shows that the CLI executes correctly without any line ending issues:
```
$ ./bin/cli.js --version
Knex CLI version: 3.1.0
Knex Local version: 3.1.0
```

The file now properly uses LF line endings as confirmed by examining the raw bytes of the shebang line, which shows `\n` (0x0A) instead of `\r\n` (0x0D 0x0A).

For the secondary issue mentioned by notmedia about migration files being created with CRLF endings, the migration generation code uses Node's standard fs.writeFile which respects the system's default line ending settings. With the .editorconfig in place and prettier formatting, newly created migration files should also have consistent LF line endings.

Users who experienced this issue with versions 2.4.1 or 2.5.0 should upgrade to version 2.4.2, 2.5.1, or any later version. The temporary workarounds that were suggested (using dos2unix, crlf npm package, or manually converting line endings) are no longer necessary with the fixed versions.

**Related Issues:**
- #4614 - Initial report of similar CRLF issue in earlier version (0.21.20), fixed in 0.21.21
- #5459 - PR that added additional lint checks before publishing
- #5460 - PR that improved linting configuration and fixed the recurrence
