### ISSUE TITLE
Indicate which databases support the `whereILike` clause

### ISSUE THREAD

**Issue by thomaslule** [knex/knex#5920]
Hi 👋 

I tried to execute the `whereILike` function against a sqlite database and got the error:

```
Error: select * from `test_table` where `test_column` ilike 'test%' - SQLITE_ERROR: near "ilike": syntax error
```

It would be nice to have the supported databases in the documentation https://knexjs.org/#Builder-whereILike

**Comment by mercmobily** [comment]
Hello! The SQLite error you encountered has been resolved, and your suggestion about documenting database support is valid.

When you reported this issue in January 2022, `whereILike` had just been added in PR #4779 (October 2021) but contained a bug where it generated `ILIKE` syntax for SQLite, which SQLite doesn't support. This caused the exact error you encountered: "near 'ilike': syntax error". This same bug was reported again in issue #5604 and was fixed in PR #5687, which merged on April 7, 2024.

The current implementation now correctly handles `whereILike` across different databases:

PostgreSQL uses the native `ILIKE` operator, which is a case-insensitive version of `LIKE` built into PostgreSQL (lib/query/querycompiler.js:whereILike). This is the most straightforward implementation since PostgreSQL has native support for case-insensitive pattern matching.

SQLite converts `whereILike` to `LIKE`, which is already case-insensitive by default in SQLite (lib/dialects/sqlite3/query/sqlite-querycompiler.js:whereILike). SQLite's `LIKE` operator is case-insensitive for ASCII characters by default, so no special handling is needed beyond using `LIKE` instead of `ILIKE`.

MySQL converts `whereILike` to `LIKE`, which behaves case-insensitively or case-sensitively depending on the column's collation (lib/dialects/mysql/query/mysql-querycompiler.js:whereILike). Most MySQL installations use case-insensitive collations by default (like utf8_general_ci), making `LIKE` case-insensitive.

MSSQL converts `whereILike` to `LIKE` with an explicit case-insensitive collation (`collate SQL_Latin1_General_CP1_CI_AS`) to ensure consistent case-insensitive behaviour regardless of the database's default collation (lib/dialects/mssql/query/mssql-querycompiler.js:whereILike).

Your suggestion to document which databases support `whereILike` is valuable even though the bug is now fixed. The documentation at docs/src/guide/query-builder.md doesn't explain the cross-database implementation differences or note that the behaviour is emulated on databases without native `ILIKE` support. Adding this information would help users understand that while `whereILike` works across all supported databases, the implementation varies, and in some cases (like MySQL) the case-insensitivity depends on database collation settings.

Related issues:
- #5604 - whereILike and orWhereILike don't work with sqlite3 (CLOSED, duplicate of this issue)
- #5687 - Fix whereILike issue with sqlite (PR that fixed the bug)
- #4779 - Support whereLike and whereILike (PR that originally added the feature)
- #2265 - Original feature request for whereLike/whereILike

Exact duplicates:
- #5604 - Same SQLite bug, reported later and linked to the PR that fixed it

**Comment by aureateAnatidae** [comment]
I came across this issue as well. It's indeed fixed, as far as I can tell from the source code, but since the latest release was before that fix, the issue remains on the latest available version on npm.  I imagine this won't be the last time someone comes across this issue. 

While we patiently await a new release of knex (thanks for your hard work #6321), will we be advised to take the dependency from git, possibly at a commit hash? In my case, I'd follow [these instructions]( https://pnpm.io/next/package-sources#git-repository) as a pnpm user.

**Comment by mercmobily** [comment]
Well we are releasing soon. Like, very very soon. And will be releasing consistently from then on (we are finalising the release script). It's long overdue, that's for sure! The current HEAD is so much better than the current release... we shouldn't fall this far behind ever again.
